<?php
/**
 * @var Index $block
 */
use Hiberus\Curso\Block\Index;
$exam=$block->getExams();
$maxMarks=$block->getMaxMarks();
$evaluation="";
//var_dump($maxMarks);
$defaultMark=$block->getDefaultMark();
$elements=$block->getElements();
$iterable=0;
?>
<h2 class="title">Exam</h2>
    <?php
    foreach ($exam as $item){
        if ($iterable++ == $elements && $elements>0){
            break;
        }   ?>
<ul>
    <li><?=$item->getFirstname()?></li>
    <li><?=$item->getLastname()?></li>
    <?php
    if($item->getMark() >= $defaultMark){
        $evaluation="aprobado";
    }else{
        $evaluation="suspenso";
    }

    if(array_search($item->getMark(),$maxMarks)){
        ?>
        <li class="<?=$evaluation?>"><strong><?=$item->getMark()?></strong></li>
        <?php
    }else{
        ?>
        <li class="<?=$evaluation?>"><?=$item->getMark()?></li>
        <?php
    }
    ?>
</ul>
    <?php } ?>
<p><?= __('Total number of %1 students', [count($exam)]) ?></p>
<p><?= __('Average Exam marks %1', [$block->getAverageMarks()]) ?></p>
